---
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: NGINX | Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start nginx

- name: NGINX | Create general config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Reload nginx

- name: Lighthouse | install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: Lighthouse | Copy from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"

- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: Reload nginx